services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
      - keycloak-network
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"

networks:
  keycloak-network:
    name: keycloak-network
    driver: bridge
    external: true
