services:
  web:
    build:
      args:
        - NODEMON_VERSION=${NODEMON_VERSION:-3.1.10}
      context: .
      dockerfile: Dockerfile.dev
    # command: npm run dev
    volumes:
      - .:/home/node/app
    env_file:
      - .env
    #   - path: .env.override
    #     required: false
    depends_on:
      db:
        condition: service_healthy
    #   # restart: true
    # networks:
    #   - extermal-api_default
    extra_hosts:
      - "host.docker.internal:host-gateway"
